from social_hunter.models import EngineHandoffContract, SourceCapability, TargetType

SOURCE_CAPABILITIES = [
    SourceCapability(
        id="whatsmyname-import",
        name="WhatsMyName Dataset Import",
        category="username_profile",
        target_types=[TargetType.username],
        status="stubbed",
        terms_note="Use the published dataset under its project license and preserve attribution.",
        data_returned=["source", "category", "profile_url", "existence_signal", "confidence"],
    ),
    SourceCapability(
        id="github-users",
        name="GitHub REST Users API",
        category="username_profile",
        target_types=[TargetType.username],
        status="needs_api_key",
        terms_note="Use public user profile endpoints and provider tokens only where allowed by GitHub terms.",
        data_returned=["profile_url", "public_email", "company", "blog", "location", "public_repos"],
    ),
    SourceCapability(
        id="reddit-api",
        name="Reddit API",
        category="username_profile",
        target_types=[TargetType.username],
        status="needs_api_key",
        terms_note="Use Reddit API access for public profile metadata and respect API policy and rate limits.",
        data_returned=["profile_url", "karma", "account_created", "public_activity_signal"],
    ),
    SourceCapability(
        id="x-user-lookup",
        name="X API User Lookup",
        category="username_profile",
        target_types=[TargetType.username],
        status="needs_api_key",
        terms_note="Requires an approved X API tier; store bearer tokens through Vault references.",
        data_returned=["profile_url", "display_name", "bio", "verified", "public_metrics"],
    ),
    SourceCapability(
        id="public-profile-sources",
        name="Additional Public Profile Sources",
        category="username_profile",
        target_types=[TargetType.username],
        status="stubbed",
        terms_note="Planned account checks for Mastodon, GitLab, Stack Overflow, and other public profile endpoints.",
        data_returned=["profile_url", "existence_signal", "public_metadata", "confidence"],
    ),
    SourceCapability(
        id="hunter",
        name="Hunter.io",
        category="email_intel",
        target_types=[TargetType.email, TargetType.domain],
        status="needs_api_key",
        terms_note="Use domain search, email finder, verifier, and enrichment only for authorized business/contact workflows.",
        data_returned=["email", "domain", "confidence", "verification_status", "source_urls"],
    ),
    SourceCapability(
        id="hibp",
        name="Have I Been Pwned",
        category="email_intel",
        target_types=[TargetType.email, TargetType.domain],
        status="needs_api_key",
        terms_note="Requires paid API key and terms-compliant usage for email/domain lookups.",
        data_returned=["breach_name", "breach_date", "domain", "data_classes"],
    ),
    SourceCapability(
        id="email-validation",
        name="Email Validation Provider",
        category="email_intel",
        target_types=[TargetType.email],
        status="needs_api_key",
        terms_note="Use a provider account with permission for validation and enrichment.",
        data_returned=["syntax_valid", "deliverability", "mx_records", "disposable_flag"],
    ),
    SourceCapability(
        id="people-data-labs",
        name="People Data Labs",
        category="person_enrichment",
        target_types=[TargetType.email, TargetType.domain, TargetType.ip],
        status="needs_api_key",
        terms_note="Use only licensed enrichment/search endpoints with consent or legitimate-interest controls.",
        data_returned=["person_profile", "company", "social_urls", "job_title", "location", "confidence"],
    ),
    SourceCapability(
        id="fullcontact-slot",
        name="FullContact-style Enrichment Slot",
        category="person_enrichment",
        target_types=[TargetType.email, TargetType.domain],
        status="disabled",
        terms_note="Reserved for a licensed person/company enrichment provider with normalized results.",
        data_returned=["person_profile", "company_profile", "social_urls", "confidence"],
    ),
    SourceCapability(
        id="twilio-lookup",
        name="Twilio Lookup v2",
        category="phone_intel",
        target_types=[TargetType.phone],
        status="needs_api_key",
        terms_note="Validate and classify phone numbers; do not use as private phone discovery.",
        data_returned=["e164", "line_type", "carrier", "caller_name", "sim_swap", "reassigned_number", "risk"],
    ),
    SourceCapability(
        id="ipinfo",
        name="IPinfo",
        category="domain_intel",
        target_types=[TargetType.ip],
        status="needs_api_key",
        terms_note="Requires provider token for non-demo usage.",
        data_returned=["asn", "org", "country", "region", "city", "privacy_flags"],
    ),
    SourceCapability(
        id="web-search-indexes",
        name="Search Index APIs",
        category="web_search",
        target_types=[TargetType.username, TargetType.email, TargetType.domain],
        status="needs_api_key",
        terms_note="Connector slot for Brave Search, SerpApi, Bing Web Search, Tavily, Exa, or legacy Google CSE customers.",
        data_returned=["result_url", "title", "snippet", "source_engine", "rank"],
    ),
    SourceCapability(
        id="business-contact-data",
        name="Business / Local Contact Data",
        category="business_contact",
        target_types=[TargetType.domain],
        status="needs_api_key",
        terms_note="Use business/public-place data providers for organizations, not private personal contact discovery.",
        data_returned=["business_name", "website", "phone", "address", "category", "source_url"],
    ),
    SourceCapability(
        id="opencorporates",
        name="OpenCorporates",
        category="business_contact",
        target_types=[TargetType.domain],
        status="stubbed",
        terms_note="Use company registry data under provider terms and preserve source attribution.",
        data_returned=["company_name", "jurisdiction", "registry_url", "officers_if_public"],
    ),
    SourceCapability(
        id="rdap-whois",
        name="WHOIS / RDAP",
        category="domain_intel",
        target_types=[TargetType.domain],
        status="stubbed",
        terms_note="Use public RDAP responses and avoid storing unnecessary personal registrant details.",
        data_returned=["registrar", "nameservers", "registration_dates", "status", "rdap_url"],
    ),
    SourceCapability(
        id="securitytrails",
        name="SecurityTrails",
        category="domain_intel",
        target_types=[TargetType.domain],
        status="needs_api_key",
        terms_note="Licensed DNS, subdomain, and infrastructure intelligence provider.",
        data_returned=["dns_records", "subdomains", "historical_dns", "associated_ips"],
    ),
    SourceCapability(
        id="builtwith-wappalyzer",
        name="BuiltWith / Wappalyzer",
        category="domain_intel",
        target_types=[TargetType.domain],
        status="needs_api_key",
        terms_note="Technology profiling for domains and company asset context.",
        data_returned=["technologies", "analytics_tags", "hosting", "frameworks"],
    ),
    SourceCapability(
        id="dnsdb-style",
        name="DNSDB-style Passive DNS",
        category="domain_intel",
        target_types=[TargetType.domain, TargetType.ip],
        status="needs_api_key",
        terms_note="Use licensed passive DNS datasets for domain/infrastructure investigations.",
        data_returned=["rrsets", "first_seen", "last_seen", "related_domains", "related_ips"],
    ),
    SourceCapability(
        id="external-engine-slot",
        name="Separate Engine Slot",
        category="external",
        target_types=[TargetType.username, TargetType.email, TargetType.domain, TargetType.ip, TargetType.phone],
        status="disabled",
        terms_note="Only attach engines that provide lawful, authorized, terms-compliant results.",
        data_returned=["normalized_findings"],
    ),
]


def engine_contract() -> EngineHandoffContract:
    return EngineHandoffContract(
        accepted_input={
            "target_type": "username | email | domain | ip | phone",
            "target": "Normalized target string",
            "search_id": "UUID generated by Social Hunter",
            "source_groups": "Requested source families",
            "consent_confirmed": "Boolean authorization gate required for searches",
            "dry_run": "Default true for classroom and staging workflows",
        },
        expected_output_fields=[
            "source",
            "category",
            "status",
            "confidence",
            "title",
            "url",
            "evidence",
            "checked_at",
            "compliance_flags",
        ],
        prohibited_capabilities=[
            "CAPTCHA bypass",
            "stealth browser fingerprint evasion",
            "aggressive rate-limit evasion",
            "credential/session-cookie use without explicit authorization",
            "raw secret or cookie return values",
        ],
        integration_notes=[
            "Return normalized findings only; do not return raw private payloads.",
            "Every result must include source attribution and a confidence score.",
            "The engine must declare source terms and rate-limit behavior before activation.",
            "Provider credentials must be injected through Vault-backed runtime configuration.",
            "Contact/account/phone providers must remain API-first and terms-compliant.",
            "Phone connectors validate known numbers; they are not private phone-number discovery tools.",
        ],
    )
