from social_hunter.models import EngineHandoffContract, SourceCapability, TargetType

SOURCE_CAPABILITIES = [
    SourceCapability(
        id="whatsmyname-import",
        name="WhatsMyName Dataset Import",
        category="username",
        target_types=[TargetType.username],
        status="stubbed",
        terms_note="Use the published dataset under its project license and preserve attribution.",
        data_returned=["source", "category", "profile_url", "existence_signal", "confidence"],
    ),
    SourceCapability(
        id="hibp",
        name="Have I Been Pwned",
        category="breach",
        target_types=[TargetType.email, TargetType.domain],
        status="needs_api_key",
        terms_note="Requires paid API key and terms-compliant usage for email/domain lookups.",
        data_returned=["breach_name", "breach_date", "domain", "data_classes"],
    ),
    SourceCapability(
        id="ipinfo",
        name="IPinfo",
        category="ip",
        target_types=[TargetType.ip],
        status="needs_api_key",
        terms_note="Requires provider token for non-demo usage.",
        data_returned=["asn", "org", "country", "region", "city", "privacy_flags"],
    ),
    SourceCapability(
        id="email-validation",
        name="Email Validation Provider",
        category="email",
        target_types=[TargetType.email],
        status="needs_api_key",
        terms_note="Use a provider account with permission for validation and enrichment.",
        data_returned=["syntax_valid", "deliverability", "mx_records", "disposable_flag"],
    ),
    SourceCapability(
        id="external-engine-slot",
        name="Separate Engine Slot",
        category="external",
        target_types=[TargetType.username, TargetType.email, TargetType.domain, TargetType.ip],
        status="disabled",
        terms_note="Only attach engines that provide lawful, authorized, terms-compliant results.",
        data_returned=["normalized_findings"],
    ),
]


def engine_contract() -> EngineHandoffContract:
    return EngineHandoffContract(
        accepted_input={
            "target_type": "username | email | domain | ip",
            "target": "Normalized target string",
            "search_id": "UUID generated by Social Hunter",
            "source_groups": "Requested source families",
        },
        expected_output_fields=[
            "source",
            "category",
            "status",
            "confidence",
            "title",
            "url",
            "evidence",
            "checked_at",
            "compliance_flags",
        ],
        prohibited_capabilities=[
            "CAPTCHA bypass",
            "stealth browser fingerprint evasion",
            "aggressive rate-limit evasion",
            "credential/session-cookie use without explicit authorization",
            "raw secret or cookie return values",
        ],
        integration_notes=[
            "Return normalized findings only; do not return raw private payloads.",
            "Every result must include source attribution and a confidence score.",
            "The engine must declare source terms and rate-limit behavior before activation.",
            "Provider credentials must be injected through Vault-backed runtime configuration.",
        ],
    )
