"""PDF report generation for Social Hunter."""
import os
import tempfile
from datetime import datetime, timezone

import markdown
from weasyprint import HTML, CSS

from social_hunter.models import SearchResponse
from social_hunter.services.reports import render_markdown_report


# PDF styling - professional report template
PDF_STYLES = """
@page {
    size: letter;
    margin: 2.5cm;
    @top-center {
        content: "Social Hunter - OSINT Report";
        font-size: 9pt;
        color: #666;
    }
    @bottom-center {
        content: "Page " counter(page) " of " counter(pages);
        font-size: 9pt;
        color: #666;
    }
}

body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    font-size: 11pt;
    line-height: 1.6;
    color: #333;
}

h1 {
    font-size: 24pt;
    color: #1a1a1a;
    border-bottom: 2px solid #0066cc;
    padding-bottom: 0.3em;
    margin-bottom: 1em;
}

h2 {
    font-size: 16pt;
    color: #333;
    margin-top: 1.5em;
    margin-bottom: 0.5em;
}

h3 {
    font-size: 13pt;
    color: #444;
    margin-top: 1.2em;
}

table {
    width: 100%;
    border-collapse: collapse;
    margin: 1em 0;
}

th, td {
    border: 1px solid #ddd;
    padding: 8px 12px;
    text-align: left;
}

th {
    background-color: #f5f5f5;
    font-weight: 600;
}

tr:nth-child(even) {
    background-color: #fafafa;
}

.status-found {
    color: #28a745;
    font-weight: 600;
}

.status-not-found {
    color: #dc3545;
}

.status-unknown {
    color: #ffc107;
}

.status-error {
    color: #dc3545;
}

.confidence-high {
    color: #28a745;
}

.confidence-medium {
    color: #ffc107;
}

.confidence-low {
    color: #dc3545;
}

.metadata {
    background-color: #f8f9fa;
    border-left: 4px solid #0066cc;
    padding: 1em;
    margin: 1em 0;
}

.footer {
    margin-top: 2em;
    padding-top: 1em;
    border-top: 1px solid #ddd;
    font-size: 9pt;
    color: #666;
}
"""


class PDFGenerator:
    """Generate PDF reports from search results."""

    def __init__(self):
        self.css = CSS(string=PDF_STYLES)

    def _enhance_markdown(self, markdown_content: str, search: SearchResponse) -> str:
        """Enhance markdown with HTML styling."""
        # Add header with logo/branding
        header = f"""
        <div class="metadata">
            <strong>Report Generated:</strong> {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}<br>
            <strong>Target Type:</strong> {search.target_type.value}<br>
            <strong>Target:</strong> {search.target}<br>
            <strong>Status:</strong> {search.status}<br>
            <strong>Findings:</strong> {len(search.findings)}
        </div>
        """

        # Convert markdown to HTML
        html_content = markdown.markdown(
            markdown_content,
            extensions=['tables', 'fenced_code']
        )

        # Wrap in full HTML document
        full_html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <title>Social Hunter Report</title>
        </head>
        <body>
            <h1>OSINT Investigation Report</h1>
            {header}
            {html_content}
            <div class="footer">
                <p>Generated by Social Hunter - Educational OSINT Platform</p>
                <p>This report is for educational purposes only. Verify all findings independently.</p>
            </div>
        </body>
        </html>
        """

        return full_html

    async def generate_pdf(self, search: SearchResponse) -> bytes:
        """Generate PDF from search response."""
        # Generate markdown first
        markdown_content = render_markdown_report(search)

        # Convert to enhanced HTML
        html_content = self._enhance_markdown(markdown_content, search)

        # Generate PDF with WeasyPrint
        html = HTML(string=html_content)
        pdf_bytes = html.write_pdf(stylesheets=[self.css])

        return pdf_bytes

    async def generate_pdf_with_metadata(
        self,
        search: SearchResponse,
        include_raw: bool = False,
    ) -> tuple[bytes, str]:
        """Generate PDF with filename."""
        pdf_bytes = await self.generate_pdf(search)

        # Generate filename
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        target_safe = "".join(c for c in search.target if c.isalnum())[:30]
        filename = f"socialhunter_{search.target_type.value}_{target_safe}_{timestamp}.pdf"

        return pdf_bytes, filename


pdf_generator = PDFGenerator()
